apiVersion: apps/v1
kind: Deployment
metadata:
  name: ProgPython-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ProgPythondeployment
  template:
    metadata:
      labels:
        app: ProgPythondeployment
    spec:
      containers:
      - name: ProgPythondeployment
        image: ProgPython:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

  