apiVersion: v1
kind: Service
metadata:
  name: prog-python-service
  namespace: default
spec:
  selector:
    app: prog-python
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP